# Generated by Django 3.2.13 on 2022-05-26 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0d3891c6-ea3f-4f02-91e0-726cf5f7545d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
